# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(630, 765)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(270, 30, 311, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.target = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.target.setObjectName("target")
        self.verticalLayout.addWidget(self.target)
        self.user = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.user.setObjectName("user")
        self.verticalLayout.addWidget(self.user)
        self.cores = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.cores.setObjectName("cores")
        self.verticalLayout.addWidget(self.cores)
        self.protocol = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.protocol.setObjectName("protocol")
        self.protocol.addItem("")
        self.protocol.addItem("")
        self.verticalLayout.addWidget(self.protocol)
        self.port = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.port.setObjectName("port")
        self.verticalLayout.addWidget(self.port)
        self.password_file = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.password_file.setObjectName("password_file")
        self.verticalLayout.addWidget(self.password_file)
        self.network_check = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.network_check.setObjectName("network_check")
        self.network_check.addItem("")
        self.network_check.addItem("")
        self.verticalLayout.addWidget(self.network_check)
        self.RunAttack = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.RunAttack.setObjectName("RunAttack")
        self.verticalLayout.addWidget(self.RunAttack)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(70, 40, 191, 451))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.open_dictionnary = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.open_dictionnary.setObjectName("open_dictionnary")
        self.verticalLayout_2.addWidget(self.open_dictionnary)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.quit = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.quit.setObjectName("quit")
        self.verticalLayout_2.addWidget(self.quit)
        self.log_window = QtWidgets.QPlainTextEdit(Dialog)
        self.log_window.setGeometry(QtCore.QRect(23, 549, 591, 211))
        self.log_window.setObjectName("log_window")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.target.setText(_translate("Dialog", "127.0.0.1"))
        self.user.setText(_translate("Dialog", "root"))
        self.cores.setText(_translate("Dialog", "4"))
        self.protocol.setItemText(0, _translate("Dialog", "ssh"))
        self.protocol.setItemText(1, _translate("Dialog", "mysql"))
        self.port.setText(_translate("Dialog", "22"))
        self.network_check.setItemText(0, _translate("Dialog", "yes"))
        self.network_check.setItemText(1, _translate("Dialog", "no"))
        self.RunAttack.setText(_translate("Dialog", "Run Attack"))
        self.label_8.setText(_translate("Dialog", "Target"))
        self.label_9.setText(_translate("Dialog", "Username"))
        self.label_3.setText(_translate("Dialog", "Cores"))
        self.label_4.setText(_translate("Dialog", "Protocol"))
        self.open_dictionnary.setText(_translate("Dialog", "Open Dictionnary"))
        self.label_5.setText(_translate("Dialog", "Port"))
        self.label_7.setText(_translate("Dialog", "Network checks"))
        self.quit.setText(_translate("Dialog", "Quit"))

